# Generated by Django 4.1.5 on 2023-02-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_myorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrders',
        ),
    ]
