# Generated by Django 4.1.5 on 2023-02-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_cart'),
        ('seller', '0006_myorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyOrders',
            new_name='MyOrder',
        ),
    ]
