# Generated by Django 4.1.5 on 2023-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_rename_myorders_myorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='gst_no',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
